// <auto-generated />
using System;
using LinkUp_REST_API.Data.DbContextConnections;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkUp_REST_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinkUp_REST_API.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("FavoriteProfiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameOfEducation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationId");

                    b.HasIndex("KeywordId")
                        .IsUnique();

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Keyword", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EducationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("KeywordId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Media", b =>
                {
                    b.Property<string>("MediaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Pending.AudienceSpecification", b =>
                {
                    b.Property<Guid>("AudienceSpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AudienceSpecificationId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("AudienceSpecifications");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Pending.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PortfolioId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.PersonInformation", b =>
                {
                    b.Property<Guid>("PersonInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonInformationId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("PersonInformation");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Pitch", b =>
                {
                    b.Property<Guid>("PitchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipientProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PitchId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Pitches");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AudienceSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.HasIndex("AccountId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Education", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Keyword", "Keyword")
                        .WithOne("Education")
                        .HasForeignKey("LinkUp_REST_API.Models.Education", "KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Keyword", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Profile", "Profile")
                        .WithOne("Keyword")
                        .HasForeignKey("LinkUp_REST_API.Models.Keyword", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Media", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Profile", "Profile")
                        .WithOne("ProfilePicture")
                        .HasForeignKey("LinkUp_REST_API.Models.Media", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Pending.AudienceSpecification", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Profile", "Profile")
                        .WithOne("AudienceSpecification")
                        .HasForeignKey("LinkUp_REST_API.Models.Pending.AudienceSpecification", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Pending.Portfolio", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Profile", "Profile")
                        .WithOne("Portfolio")
                        .HasForeignKey("LinkUp_REST_API.Models.Pending.Portfolio", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.PersonInformation", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Account", null)
                        .WithOne("PersonInformation")
                        .HasForeignKey("LinkUp_REST_API.Models.PersonInformation", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Pitch", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Profile", "Profile")
                        .WithMany("Pitches")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Profile", b =>
                {
                    b.HasOne("LinkUp_REST_API.Models.Account", "Account")
                        .WithMany("Profiles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Account", b =>
                {
                    b.Navigation("PersonInformation")
                        .IsRequired();

                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Keyword", b =>
                {
                    b.Navigation("Education");
                });

            modelBuilder.Entity("LinkUp_REST_API.Models.Profile", b =>
                {
                    b.Navigation("AudienceSpecification");

                    b.Navigation("Keyword");

                    b.Navigation("Pitches");

                    b.Navigation("Portfolio");

                    b.Navigation("ProfilePicture");
                });
#pragma warning restore 612, 618
        }
    }
}
