// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_API.Data;

#nullable disable

namespace REST_API.Migrations
{
    [DbContext(typeof(MssqlContext))]
    partial class MssqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REST_API.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountId");

                    b.HasIndex("PersonInformationId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("REST_API.Models.AudienceSpecification", b =>
                {
                    b.Property<Guid>("AudienceSpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Professions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AudienceSpecificationId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("AudienceSpecifications");
                });

            modelBuilder.Entity("REST_API.Models.Education", b =>
                {
                    b.Property<Guid>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GraduationYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameOfEducation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EducationId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("REST_API.Models.Keyword", b =>
                {
                    b.Property<Guid>("KeywordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EducationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("KeywordId");

                    b.HasIndex("EducationId")
                        .IsUnique()
                        .HasFilter("[EducationId] IS NOT NULL");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("REST_API.Models.PersonInformation", b =>
                {
                    b.Property<Guid>("PersonInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonInformationId");

                    b.ToTable("PersonInformation");
                });

            modelBuilder.Entity("REST_API.Models.Pitch", b =>
                {
                    b.Property<Guid>("PitchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TextMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PitchId");

                    b.HasIndex("ProfileId");

                    b.ToTable("Pitches");
                });

            modelBuilder.Entity("REST_API.Models.Portfolio", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Projects")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PortfolioId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("PortfolioItems");
                });

            modelBuilder.Entity("REST_API.Models.Profile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AudienceSpecificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KeywordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFlagged")
                        .HasColumnType("bit");

                    b.HasKey("ProfileId");

                    b.HasIndex("AccountId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("REST_API.Models.Account", b =>
                {
                    b.HasOne("REST_API.Models.PersonInformation", "PersonInformation")
                        .WithMany()
                        .HasForeignKey("PersonInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInformation");
                });

            modelBuilder.Entity("REST_API.Models.AudienceSpecification", b =>
                {
                    b.HasOne("REST_API.Models.Profile", "Profile")
                        .WithOne("AudienceSpecification")
                        .HasForeignKey("REST_API.Models.AudienceSpecification", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("REST_API.Models.Keyword", b =>
                {
                    b.HasOne("REST_API.Models.Education", "Education")
                        .WithOne("Keyword")
                        .HasForeignKey("REST_API.Models.Keyword", "EducationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("REST_API.Models.Profile", "Profile")
                        .WithOne("Keyword")
                        .HasForeignKey("REST_API.Models.Keyword", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("REST_API.Models.Pitch", b =>
                {
                    b.HasOne("REST_API.Models.Profile", "Profile")
                        .WithMany("Pitches")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("REST_API.Models.Portfolio", b =>
                {
                    b.HasOne("REST_API.Models.Profile", "Profile")
                        .WithOne("Portfolio")
                        .HasForeignKey("REST_API.Models.Portfolio", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("REST_API.Models.Profile", b =>
                {
                    b.HasOne("REST_API.Models.Account", "Account")
                        .WithMany("Profiles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("REST_API.Models.Account", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("REST_API.Models.Education", b =>
                {
                    b.Navigation("Keyword")
                        .IsRequired();
                });

            modelBuilder.Entity("REST_API.Models.Profile", b =>
                {
                    b.Navigation("AudienceSpecification");

                    b.Navigation("Keyword");

                    b.Navigation("Pitches");

                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
